#!/usr/bin/env ruby

require 'json'

begin
	  ashrc = "./.ashrc"
	    f = File.open(ashrc, 'r')
rescue
	  ashrc = ENV['HOME'] + "/.ashrc"
	    f = File.open(ashrc, 'r')
end


$tunnel = ""
host = ARGV[0]
$default_profile = "Pro"

json = f.read
hash = JSON.parse(json)

stuff = hash.select{|key, hash| key=""}

stuff.each do|k,v|
    v.each do|key, value|
      case key
        when "fqdn"
         puts value
      end
    end
end

